#!/bin/bash
# ============================================
# GHOST DOCKER SETUP SCRIPT
# ============================================
# This script generates Nginx config from .env

set -e

# Load environment variables
if [ ! -f .env ]; then
    echo "❌ Error: .env file not found!"
    echo "   Copy .env.example to .env and configure it first:"
    echo "   cp .env.example .env"
    exit 1
fi

source .env

# Validate required variables
if [ -z "$DOMAIN" ] || [ -z "$GHOST_PORT" ] || [ -z "$CONTAINER_PREFIX" ]; then
    echo "❌ Error: Missing required variables in .env"
    echo "   Required: DOMAIN, GHOST_PORT, CONTAINER_PREFIX"
    exit 1
fi

echo "🔧 Generating Nginx config for: $DOMAIN"
echo "   Ghost Port: $GHOST_PORT"
echo "   Container Prefix: $CONTAINER_PREFIX"

# Generate Nginx config
cat > nginx/${CONTAINER_PREFIX}.conf << EOF
# ============================================
# ${DOMAIN} - NGINX CONFIGURATION
# ============================================
# Generated by setup.sh
# Copy to: /etc/nginx/sites-available/${CONTAINER_PREFIX}

# Rate limiting zone
limit_req_zone \$binary_remote_addr zone=${CONTAINER_PREFIX}_login:10m rate=5r/m;
limit_req_zone \$binary_remote_addr zone=${CONTAINER_PREFIX}_api:10m rate=30r/m;

# Upstream Ghost
upstream ${CONTAINER_PREFIX}_upstream {
    server 127.0.0.1:${GHOST_PORT};
    keepalive 64;
}

# Redirect HTTP to HTTPS
server {
    listen 80;
    listen [::]:80;
    server_name ${DOMAIN};
    
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }
    
    location / {
        return 301 https://\$server_name\$request_uri;
    }
}

# HTTPS Server
server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name ${DOMAIN};

    # SSL Configuration
    ssl_certificate /etc/letsencrypt/live/${DOMAIN}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/${DOMAIN}/privkey.pem;
    ssl_session_timeout 1d;
    ssl_session_cache shared:SSL:50m;
    ssl_session_tickets off;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384;
    ssl_prefer_server_ciphers off;

    # Security Headers
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

    # Logging
    access_log /var/log/nginx/${CONTAINER_PREFIX}.access.log;
    error_log /var/log/nginx/${CONTAINER_PREFIX}.error.log;

    # Rate Limiting for Login
    location /ghost/api/admin/session {
        limit_req zone=${CONTAINER_PREFIX}_login burst=3 nodelay;
        limit_req_status 429;
        proxy_pass http://${CONTAINER_PREFIX}_upstream;
        include /etc/nginx/snippets/proxy-params.conf;
    }

    # Rate Limiting for API
    location /ghost/api/ {
        limit_req zone=${CONTAINER_PREFIX}_api burst=50 nodelay;
        proxy_pass http://${CONTAINER_PREFIX}_upstream;
        include /etc/nginx/snippets/proxy-params.conf;
    }

    # Static Assets (Caching)
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)\$ {
        proxy_pass http://${CONTAINER_PREFIX}_upstream;
        expires 7d;
        add_header Cache-Control "public, immutable";
        include /etc/nginx/snippets/proxy-params.conf;
    }

    # Main Proxy
    location / {
        proxy_pass http://${CONTAINER_PREFIX}_upstream;
        include /etc/nginx/snippets/proxy-params.conf;
    }

    # Block hidden files
    location ~ /\. {
        deny all;
        return 404;
    }

    # Block PHP
    location ~* \.php\$ {
        deny all;
        return 404;
    }
}
EOF

echo "✅ Nginx config generated: nginx/${CONTAINER_PREFIX}.conf"
echo ""
echo "📋 Next steps on your server:"
echo "   1. Copy config:  sudo cp nginx/${CONTAINER_PREFIX}.conf /etc/nginx/sites-available/${CONTAINER_PREFIX}"
echo "   2. Enable site:  sudo ln -sf /etc/nginx/sites-available/${CONTAINER_PREFIX} /etc/nginx/sites-enabled/"
echo "   3. Get SSL:      sudo certbot --nginx -d ${DOMAIN}"
echo "   4. Start Ghost:  docker-compose up -d"
echo ""
echo "🌐 Your site will be at: https://${DOMAIN}"
